name: Build and Release JAR

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Set up JDK 13 
      uses: actions/setup-java@v1
      with:
        java-version: 13 
    - name: package
      run: mvn --no-transfer-progress package
    - name: Upload to release
      uses: L1NNA/github-release@master
      with:
        tag: v0.0.1
        files: target/jarv1s-ghidra.jar 
        body: latest jar built
        token: ${{ secrets.GITHUB_TOKEN }}
        allow_override: true
