name: Build and Release JAR

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Set up JDK 13 
      uses: actions/setup-java@v1
      with:
        java-version: 13 
    - name: package
      run: mvn package
    - name: Upload to release
      uses: meeDamian/github-release@1.0
      with:
        tag: v0.0.1
        files: target/jarv1s-ghidra.jar 
        body: latest jar built
        token: ${{ secrets.GITHUB_TOKEN }}
        allow_override: true
