name: Build and Release JAR

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/maven.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/maven.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Set up JDK 13 
      uses: actions/setup-java@v1
      with:
        java-version: 13 
#     this is the jar we built locally (not the lastest)
#     (now we switch to download the latest ghidra release and build the single jar. see code below.)
#     - name: download dependencies
#       run: wget -q https://github.com/L1NNA/JARV1S-Ghidra/releases/download/ghidra-jar/ghidra-1.0.jar -P lib/nsa/ghidra/1.0/
    - name: download official Ghidra single jar
      run: |
        wget -q https://ghidra-sre.org/ghidra_9.1.2_PUBLIC_20200212.zip
        unzip -q ghidra_9.1.2_PUBLIC_20200212.zip
    - name: generate single JAR ghidra
      run: |
        ls -alh
        ./ghidra_9.1.2_PUBLIC/server/buildGhidraJar
    - name: package
      run: mvn --no-transfer-progress package
    - name: Upload to release
      uses: L1NNA/github-release@master
      with:
        tag: v0.0.1
        files: target/jarv1s-ghidra.jar 
        gzip: false
        body: latest jar built
        token: ${{ secrets.GITHUB_TOKEN }}
        allow_override: true
