name: Build and Release JAR

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Set up JDK 13 
      uses: actions/setup-java@v1
      with:
        java-version: 13 
    - name: package
      run: mvn package
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/jarv1s-ghidra.jar application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
